/* game.h -- portable grid/rules engine, ported from game.js. No platform
 * dependencies (no QDOS, no stdio) so it can be compiled and tested both
 * natively (host tests) and with qcc for the QL build. */
#ifndef GAME_H
#define GAME_H

#define BORDER 1
#define INNER_W 9 /* QLuzznic levels are solver-certified at this exact
                   * width -- see tools/gen_levels.py and asm/display.s's margin_x */
#define INNER_H 6
#define OUTER_W (INNER_W + BORDER * 2) /* 11 */
#define OUTER_H (INNER_H + BORDER * 2) /* 8 */

#define STANDARD_BLOCK_COUNT 8
#define BLOCK_TYPE_BASE 10 /* grid cell for a block = BLOCK_TYPE_BASE + colour index (0..7) */
#define STEEL 9             /* grid cell value for an indestructible wall */
/* JOKER=18 sits exactly one past the last colour value (BLOCK_TYPE_BASE+
 * STANDARD_BLOCK_COUNT-1=17), so it's automatically excluded from every
 * existing "v>=BLOCK_TYPE_BASE && v<BLOCK_TYPE_BASE+STANDARD_BLOCK_COUNT"
 * range check (counts_by_type) without changing those checks -- but
 * places that test v>=BLOCK_TYPE_BASE alone (rendering) or index an
 * array sized BLOCK_TYPE_BASE+STANDARD_BLOCK_COUNT (has_orphan_block)
 * DO need an explicit v==JOKER guard, since JOKER isn't an ordinary
 * colour: it moves and falls like a piece, but only ever matches via
 * find_joker_matches() in game.c, never the ordinary flood-fill. */
#define JOKER 18

#define PLAY_MIN_ROW BORDER
#define PLAY_MAX_ROW (OUTER_H - 1 - BORDER)
#define PLAY_MIN_COL BORDER
#define PLAY_MAX_COL (OUTER_W - 1 - BORDER)

#define LEVEL_TIME_SECONDS 120
#define TIME_BONUS_PER_SECOND 5

/* Grid's declared row width is GRID_STRIDE, not OUTER_W: OUTER_W(11)
 * is prime, so c68 can't expand a row*OUTER_W index into a couple of
 * inline shift+add instructions the way it could for the old
 * OUTER_W(10) -- it falls back to calling .Xulmul, a real multiply
 * routine pulled in from libc.a that this project never needed
 * before, and pulling it in reliably crashed the job at boot (same
 * "Job finished" symptom as every other mystery crash so far -- see
 * asm/display.s's blit_steel_half/ipc_sound.s's header for the
 * unresolved sibling cases). GRID_STRIDE(12) is >= OUTER_W and does
 * decompose cleanly (12=8+4), so indexing stays inline. Every loop
 * over grid columns is still bounded by OUTER_W, so the one padding
 * byte at the end of each row is simply never read or written. */
#define GRID_STRIDE 12

typedef unsigned char Grid[OUTER_H][GRID_STRIDE];

/* Raw level data as converted from qluzznic-levels.json: an INNER_H x
 * INNER_W block of cells, values 0 (empty), 9 (steel), 18 (joker) or
 * 1..8 (an original colour id -- NOT a sprite index; build_level()
 * remaps colours to sprite indices in first-appearance order, the same
 * remap the project's original game.js prototype used). */
/* interior's row width is LEVEL_ROW_STRIDE, not INNER_W, for the same
 * reason Grid's is GRID_STRIDE (see that comment) -- and it has to
 * satisfy that same "clean 2-power decomposition" constraint TWICE:
 * once directly (row*LEVEL_ROW_STRIDE, indexing within one level's
 * interior[][]) and once multiplied by INNER_H (INNER_H*LEVEL_ROW_STRIDE
 * = sizeof(LevelDef), for LEVELS[level_index] indexing). INNER_H(6)*
 * INNER_W(9)=54=32+16+4+2 (a 4-term sum) fails the second check, which
 * is what sent this down this path in the first place. LEVEL_ROW_STRIDE
 * (12)=8+4 passes the direct check, and INNER_H(6)*12=72=64+8 passes
 * the sizeof(LevelDef) check too. Every level's real data still only
 * ever fills the first INNER_W columns of each row -- see
 * tools/gen_levels.py, which pads the rest with 0. */
#define LEVEL_ROW_STRIDE 12
typedef struct {
    unsigned char interior[INNER_H][LEVEL_ROW_STRIDE];
} LevelDef;

/* Generated by tools/gen_levels.py from qluzznic-levels.json: the
 * game's own 100-level, solver-certified campaign, in the same order. */
extern const int LEVEL_COUNT;
extern const LevelDef LEVELS[];

/* First LEVELS[] index containing a JOKER cell (-1 if none), computed
 * by tools/gen_levels.py -- used by game_loop.c to show a one-time
 * explanation screen before the player first meets the joker. */
extern const int FIRST_JOKER_LEVEL;

typedef struct {
    unsigned short row;
    unsigned short col;
} Cell;

/* Game state the caller owns and drives; the engine only ever touches
 * grid/score/etc through these functions, mirroring the JS globals. */
typedef struct {
    Grid grid;
    int score;
    int current_level_index;
} GameState;

void empty_grid(Grid grid);

/* Builds `grid` from a level definition: colours remapped to
 * BLOCK_TYPE_BASE+i in first-appearance order (row-major scan),
 * matching game.js's colorsUsed()+remap exactly. Caller/level-data
 * pipeline must only supply levels with 1..STANDARD_BLOCK_COUNT distinct
 * colours (like game.js's LEVELS filter) -- a 9th distinct colour is
 * silently dropped as empty rather than rejected here. */
void build_level(const LevelDef *level, Grid grid);

/* Lets blocks fall within each column's steel-bounded segments. */
void apply_gravity(Grid grid);

/* Flood-fills connected same-colour groups (size >= 2) and writes their
 * cells into `out` (capacity INNER_W*INNER_H). Returns the count. */
int find_matches(Grid grid, Cell *out);

/* Instant (non-animated) stabilisation: repeatedly applies gravity and
 * clears matches until stable, awarding chain-bonus score exactly like
 * game.js's settle(). Returns total cells cleared. */
int settle(Grid grid, int *score);

int is_grid_empty(Grid grid);

/* True if some block can still slide into an adjacent empty cell. */
int has_any_move(Grid grid);

/* True if the board is unsolvable: more colours have exactly one
 * instance left than there are jokers to rescue them (a joker can
 * pair with one lone colour and clear with it, but only one -- see
 * game.h's JOKER comment and [[qluzznic-own-levels-and-joker]]). */
int has_orphan_block(Grid grid);

/* [top, bottom] rows of the steel-bounded segment of column `col`
 * containing `row` (used by move logic to know how far a dropped block
 * settles within its column). */
void segment_bounds(Grid grid, int col, int row, int *top, int *bottom);

/* Attempts to slide the block at (row,col) sideways by dc (+-1 column).
 * Rejects (returns 0, grid unchanged) if out of bounds, the source cell
 * has no movable block, or the target cell is occupied -- exactly
 * game.js's moveBlock() guard clauses. On success (returns 1) the block
 * is relocated to (row, col+dc) in `grid`; caller must then call
 * settle() and cursor_landing_row() to find where gravity leaves it,
 * matching the JS runSettleAnimated flow. */
int move_block(Grid grid, int row, int col, int dc, int *target_col);

/* After move_block()+settle(), finds where the cursor should follow to:
 * the topmost remaining block in target_col's steel-bounded segment
 * containing seg_row, or the segment bottom if it's now empty (matches
 * game.js's post-settle cursor-follow scan). */
int cursor_landing_row(Grid grid, int target_col, int seg_row);

typedef struct {
    unsigned char col;
    unsigned char from_row;
    unsigned char to_row;
    unsigned char type;
} Faller;

/* Applies gravity (like apply_gravity) and returns which blocks moved,
 * for the fall animation -- matches game.js's computeFallers(). `out`
 * capacity must be INNER_W*INNER_H (worst case: every block moves). */
int compute_fallers(Grid grid, Faller *out);

/* Per-type remaining counts, out[i] = count of BLOCK_TYPE_BASE+i cells
 * (out must have STANDARD_BLOCK_COUNT entries). */
void counts_by_type(Grid grid, int *out);

#endif
