#!/usr/bin/env python3
"""Convert qluzznic-levels.json's exclusive campaign into a C array of
LevelDef structs. The original 117 GPL Vexed levels were dropped from
the build (QLuzznic now ships only its own, solver-certified levels)
-- see git history / earlier revisions of this file if that parsing
code is ever needed again.

qluzznic-levels.json levels are already solver-certified at our exact
grid size (11x8 full / 9x6 interior) -- see that file's "rows" (# =
wall, . = empty, 1-8 = colour, 9 = joker). '#' maps to STEEL(9) here;
the source's own '9' (joker) maps to JOKER(18) -- game.h's JOKER value
-- NOT to our STEEL(9), since the two formats assign '9' to different
things. Colours 1-8 pass through unchanged, remapped to sprite indices
at runtime in build_level() (game.c) by first-appearance order, same
as the original Vexed levels were.
"""
import json
import sys
from pathlib import Path

INNER_W = 9
INNER_H = 6
LEVEL_ROW_STRIDE = INNER_W  # must match game.h's LEVEL_ROW_STRIDE exactly --
             # no padding (unlike the old LEVEL_ROW_STRIDE=12), see that
             # #define's comment for the memory-vs-one-.Xulmul-call tradeoff.

STEEL = 9
JOKER = 18


def qluzznic_interior_of(rows):
    """rows: 8 strings of 11 chars (full grid incl. frame). Extracts the
    9x6 interior (rows 1-6, cols 1-9) and maps symbols to our grid
    values, padded to LEVEL_ROW_STRIDE."""
    interior = []
    for row in rows[1:1 + INNER_H]:
        cells = row[1:1 + INNER_W]
        out_row = []
        for ch in cells:
            if ch == "#":
                out_row.append(STEEL)
            elif ch == ".":
                out_row.append(0)
            elif ch == "9":
                out_row.append(JOKER)
            else:
                out_row.append(int(ch))  # '1'..'8' -> colour, unchanged
        pad = LEVEL_ROW_STRIDE - INNER_W
        interior.append(out_row + [0] * pad)
    return interior


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("assets/qluzznic-levels.json")
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("src/levels.c")

    data = json.loads(src.read_text())
    valid = [qluzznic_interior_of(lvl["rows"]) for lvl in data["levels"]]

    first_joker_level = next(
        (i for i, interior in enumerate(valid)
         if any(JOKER in row for row in interior)),
        -1,
    )

    lines = []
    lines.append("/* levels.c -- auto-generated by tools/gen_levels.py from")
    lines.append(f" * {src.name}. Do not edit by hand -- regenerate instead. */")
    lines.append('#include "game.h"')
    lines.append("")
    lines.append(f"const int LEVEL_COUNT = {len(valid)};")
    lines.append(f"const int FIRST_JOKER_LEVEL = {first_joker_level}; /* -1 if none */")
    lines.append("")
    lines.append("const LevelDef LEVELS[] = {")
    for interior in valid:
        lines.append("    {")
        lines.append("        {")
        for row in interior:
            row_str = ", ".join(str(v) for v in row)
            lines.append(f"            {{{row_str}}},")
        lines.append("        }")
        lines.append("    },")
    lines.append("};")

    dst.write_text("\n".join(lines) + "\n")
    print(f"Wrote {dst}: {len(valid)} QLuzznic levels")


if __name__ == "__main__":
    main()
