#!/usr/bin/env python3
"""Convert police.png (the user's hand-drawn small font, one PNG strip)
into raw mode 8 bitmap glyph data and emit an as68 .s file.

Source layout: 39 glyphs, each 8x7 pixels (opaque, white ink / black
background -- same convention as blocks.png), laid out left to right
in a single row in this exact order: A-Z, 0-9, '.', ':', '>'. 8px wide
is already 4-pixel-group aligned (mode 8's group-alignment rule), so
this needs no horizontal padding; height is genuinely 7 rows, not
padded to 8 either -- see asm/display.s's draw_glyph, sized to match
exactly.

A 40th glyph (index 39) is synthesised here as a blank (all-zero)
image, appended after the source's 39 -- text.c's draw_char() maps
space and any other unrecognised character to it, the same way
draw_number() pads short numbers with blanks.
"""
import sys
from pathlib import Path
from PIL import Image

GLYPH_W = 8
GLYPH_H = 7
ORDER = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:>")
BLANK_INDEX = len(ORDER)  # 39


def encode_cell(img, x0):
    """Returns GLYPH_H rows * (GLYPH_W/4 groups * 2 bytes) = 7*4 = 28 bytes."""
    out = []
    for y in range(GLYPH_H):
        for g in range(GLYPH_W // 4):
            even = 0
            odd = 0
            for px in range(4):
                x = x0 + g * 4 + px
                r, g_, b = img.getpixel((x, y))[:3]
                bit = 1 if (r > 127 or g_ > 127 or b > 127) else 0
                shift = (3 - px) * 2
                if bit:
                    even |= 0b10 << shift  # G=1,F=0 (white needs R,B too)
                    odd |= 0b11 << shift   # R=1,B=1
            out.append(even & 0xFF)
            out.append(odd & 0xFF)
    return out


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("assets/police.png")
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("asm/font_data.s")

    img = Image.open(src).convert("RGB")
    assert img.height == GLYPH_H, f"expected height {GLYPH_H}, got {img.height}"
    assert img.width == GLYPH_W * len(ORDER), (
        f"expected width {GLYPH_W * len(ORDER)} ({len(ORDER)} glyphs), got {img.width}"
    )

    bytes_per_glyph = GLYPH_H * (GLYPH_W // 4 * 2)
    lines = []
    lines.append("; font_data.s -- auto-generated by tools/gen_font.py from")
    lines.append(f"; {src.name}. Do not edit by hand -- regenerate instead.")
    lines.append(f"; {len(ORDER) + 1} glyphs ('A'-'Z','0'-'9','.',':','>' + a")
    lines.append(f"; synthesised blank), {GLYPH_W}x{GLYPH_H} mode 8 pixels,")
    lines.append(f"; opaque (white ink / black bg), {bytes_per_glyph} bytes each.")
    lines.append("")
    lines.append("\t.sect\t.data")
    lines.append("\t.extern\t_font_data")
    lines.append("\t.even")
    lines.append("_font_data:")

    for i, ch in enumerate(ORDER):
        data = encode_cell(img, i * GLYPH_W)
        lines.append(f"; glyph '{ch}' (index {i})")
        for row in range(0, len(data), 16):
            chunk = data[row:row + 16]
            hex_list = ",".join(f"${b:02x}" for b in chunk)
            lines.append(f"\t.data1\t{hex_list}")

    lines.append(f"; glyph blank (index {BLANK_INDEX}) -- space / unmapped fallback")
    blank = [0] * bytes_per_glyph
    for row in range(0, len(blank), 16):
        chunk = blank[row:row + 16]
        hex_list = ",".join(f"${b:02x}" for b in chunk)
        lines.append(f"\t.data1\t{hex_list}")

    dst.write_text("\n".join(lines) + "\n")
    print(f"Wrote {dst} ({len(ORDER) + 1} glyphs, {GLYPH_W}x{GLYPH_H})")


if __name__ == "__main__":
    main()
