#!/usr/bin/env python3
"""Generate a big (16x16) opaque mode-8 bitmap font for the "LEVEL
COMPLETE" banner -- the small 8x8 HUD font (gen_font.py) only has
digits, and the banner needs to be large enough to read at a glance.
Same encoding as png2sprites.py/gen_font.py; classic 5x7 block letters,
scaled 2x (each source pixel -> a 2x2 block) into a 16x16 cell.
"""
from pathlib import Path

SRC_W, SRC_H = 5, 7
SCALE = 2
CELL = 16  # SRC_W*SCALE=10, SRC_H*SCALE=14, padded to 16x16

LETTERS = {
    "L": ["10000", "10000", "10000", "10000", "10000", "10000", "11111"],
    "E": ["11111", "10000", "10000", "11110", "10000", "10000", "11111"],
    "V": ["10001", "10001", "10001", "10001", "10001", "01010", "00100"],
    "C": ["01111", "10000", "10000", "10000", "10000", "10000", "01111"],
    "O": ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
    "M": ["10001", "11011", "10101", "10101", "10001", "10001", "10001"],
    "P": ["11110", "10001", "10001", "11110", "10000", "10000", "10000"],
    "T": ["11111", "00100", "00100", "00100", "00100", "00100", "00100"],
    "G": ["01111", "10000", "10000", "10011", "10001", "10001", "01111"],
    "A": ["01110", "10001", "10001", "11111", "10001", "10001", "10001"],
    "R": ["11110", "10001", "10001", "11110", "10100", "10010", "10001"],
    " ": ["00000", "00000", "00000", "00000", "00000", "00000", "00000"],
    # Letters needed for the title screen's "QLUZZNIC" logo (game_loop.c).
    "Q": ["01110", "10001", "10001", "10001", "10101", "10010", "01101"],
    "U": ["10001", "10001", "10001", "10001", "10001", "10001", "01110"],
    "Z": ["11111", "00001", "00010", "00100", "01000", "10000", "11111"],
    "N": ["10001", "11001", "10101", "10101", "10011", "10001", "10001"],
    "I": ["11111", "00100", "00100", "00100", "00100", "00100", "11111"],
}
ORDER = [
    "L", "E", "V", "C", "O", "M", "P", "T", "G", "A", "R", " ",
    "Q", "U", "Z", "N", "I",
]


def scaled_pattern(rows):
    """5x7 -> 10x14 (2x scale), then padded to 16x16 (left/top pad 3,
    right/bottom pad 3)."""
    big_rows = []
    for row in rows:
        scaled_row = "".join(ch * SCALE for ch in row)
        big_rows.append(scaled_row)
        big_rows.append(scaled_row)  # duplicate row too (vertical 2x)

    pad_left = (CELL - SRC_W * SCALE) // 2
    pad_right = CELL - SRC_W * SCALE - pad_left
    pad_top = (CELL - SRC_H * SCALE) // 2
    pad_bottom = CELL - SRC_H * SCALE - pad_top

    padded = ["0" * CELL] * pad_top
    for row in big_rows:
        padded.append("0" * pad_left + row + "0" * pad_right)
    padded += ["0" * CELL] * pad_bottom
    return padded


def encode_glyph(rows):
    out = []
    for row in rows:
        for g in range(CELL // 4):
            even = 0
            odd = 0
            for px in range(4):
                bit = int(row[g * 4 + px])
                shift = (3 - px) * 2
                if bit:
                    even |= 0b10 << shift
                    odd |= 0b11 << shift
            out.append(even & 0xFF)
            out.append(odd & 0xFF)
    return out


def main():
    dst = Path(__file__).resolve().parent.parent / "asm" / "banner_font_data.s"
    lines = []
    lines.append("; banner_font_data.s -- auto-generated by tools/gen_banner_font.py.")
    lines.append("; Do not edit by hand -- regenerate instead.")
    lines.append(f"; {len(ORDER)} glyphs (letters for \"LEVEL COMPLETE\" + space),")
    lines.append(f"; {CELL}x{CELL} mode 8 pixels, opaque, {CELL * (CELL // 4 * 2)} bytes each.")
    lines.append("")
    lines.append("\t.sect\t.data")
    lines.append("\t.extern\t_banner_font_data")
    lines.append("\t.even")
    lines.append("_banner_font_data:")
    for ch in ORDER:
        rows = scaled_pattern(LETTERS[ch])
        data = encode_glyph(rows)
        lines.append(f"; glyph '{ch}'")
        for row in range(0, len(data), 16):
            chunk = data[row:row + 16]
            hex_list = ",".join(f"${b:02x}" for b in chunk)
            lines.append(f"\t.data1\t{hex_list}")
    dst.write_text("\n".join(lines) + "\n")
    print(f"Wrote {dst} ({len(ORDER)} glyphs)")


if __name__ == "__main__":
    main()
