#!/usr/bin/env python3
"""Convert a logo PNG into raw mode 8 pixel data + an as68 .s file.
Same bit layout as tools/png2sprites.py, for a single non-tiled image
instead of a sprite strip.

Unlike blocks.png (already exact QL palette), the source logo art has
a slight colour-profile shift baked in from whatever tool exported it:
every pixel is one of exactly 8 colours, but 6 of the 8 are a few RGB
units off pure (e.g. (255,255,84) instead of pure yellow (255,255,0)).
That's a uniform per-colour shift, not real per-pixel anti-aliasing or
dithering (there are still only 8 distinct colours total), so
snapping each pixel to its nearest palette entry restores the intended
flat colours losslessly.

Width is padded (black, centred) to the next multiple of 4 if it
isn't already one -- mode 8's group-alignment rule, same as every
other image in this project.

The pixel-group stream is then PackBits-style compressed (added when
these two logos alone pushed the build over this 128K target's real
limit -- see [[ql-boot-crash-is-memory]]): a sequence of blocks, each
either
  - a REPEAT block: 1 header byte (bit7=0, value=count 1-127) + 1
    (even,odd) pair, meaning "output this pair `count` times", or
  - a LITERAL block: 1 header byte (bit7=1, low 7 bits=count 1-127) +
    `count` raw (even,odd) pairs to output as-is.
Decoded by asm/display.s's packbits_next_pair, shared by
blit_logo_mini/blit_logo_big. Plain flat RLE (always 1 pair per run)
was tried first and barely helped on the mini logo (its fine detail
has few long runs) -- this literal-run escape avoids ever being worse
than uncompressed while still capturing the big logo's large flat
areas."""
import sys
from pathlib import Path
from PIL import Image

PALETTE = [
    (0x00, 0x00, 0x00), (0x00, 0x00, 0xFF), (0xFF, 0x00, 0x00), (0xFF, 0x00, 0xFF),
    (0x00, 0xFF, 0x00), (0x00, 0xFF, 0xFF), (0xFF, 0xFF, 0x00), (0xFF, 0xFF, 0xFF),
]

MAX_RUN = 127  # 7 bits of count alongside the header's flag bit


def nearest_colour_index(rgb):
    best_i, best_d = 0, None
    for i, p in enumerate(PALETTE):
        d = sum((a - b) ** 2 for a, b in zip(rgb, p))
        if best_d is None or d < best_d:
            best_i, best_d = i, d
    return best_i


def encode_pairs(img, w, h):
    pairs = []
    for y in range(h):
        for g in range(w // 4):
            even = 0
            odd = 0
            for px in range(4):
                x = g * 4 + px
                idx = nearest_colour_index(img.getpixel((x, y)))
                gbit = (idx >> 2) & 1
                rbit = (idx >> 1) & 1
                bbit = idx & 1
                shift = (3 - px) * 2
                even |= (gbit << 1) << shift
                odd |= ((rbit << 1) | bbit) << shift
            pairs.append((even & 0xFF, odd & 0xFF))
    return pairs


def packbits_encode(pairs):
    out = bytearray()
    n = len(pairs)
    i = 0
    lit_buf = []

    def flush_lit():
        if lit_buf:
            out.append(0x80 | len(lit_buf))
            for (e, o) in lit_buf:
                out.append(e)
                out.append(o)
            lit_buf.clear()

    while i < n:
        j = i + 1
        while j < n and pairs[j] == pairs[i] and (j - i) < MAX_RUN:
            j += 1
        run_len = j - i
        if run_len >= 3:
            flush_lit()
            out.append(run_len)  # bit7=0: repeat block
            out.append(pairs[i][0])
            out.append(pairs[i][1])
            i = j
        else:
            lit_buf.append(pairs[i])
            i += 1
            if len(lit_buf) == MAX_RUN:
                flush_lit()
    flush_lit()
    return bytes(out)


def main():
    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    symbol = sys.argv[3]

    img = Image.open(src).convert("RGB")
    w, h = img.size
    if w % 4 != 0:
        pad_w = ((w // 4) + 1) * 4
        padded = Image.new("RGB", (pad_w, h), (0, 0, 0))
        padded.paste(img, ((pad_w - w) // 2, 0))
        img = padded
        w = pad_w

    pairs = encode_pairs(img, w, h)
    out = packbits_encode(pairs)

    lines = []
    lines.append(f"; {dst.name} -- auto-generated by tools/png2logo.py from")
    lines.append(f"; {src.name}. Do not edit by hand -- regenerate instead.")
    lines.append(f"; {w}x{h} mode 8 pixels, PackBits-compressed ({len(pairs) * 2}B raw ->")
    lines.append(f"; {len(out)}B compressed) -- see packbits_next_pair in asm/display.s.")
    lines.append("")
    lines.append("\t.sect\t.data")
    lines.append(f"\t.extern\t_{symbol}")
    lines.append("\t.even")
    lines.append(f"_{symbol}:")
    for row in range(0, len(out), 16):
        chunk = out[row:row + 16]
        hex_list = ",".join(f"${b:02x}" for b in chunk)
        lines.append(f"\t.data1\t{hex_list}")
    lines.append("")

    dst.write_text("\n".join(lines) + "\n")
    print(f"Wrote {dst} ({w}x{h}, {len(pairs) * 2}B raw -> {len(out)}B compressed)")


if __name__ == "__main__":
    main()
