#!/usr/bin/env python3
"""Convert steel_sub.png (a single 12x16, pure QL mode-8 palette tile)
into raw mode 8 pixel data and emit an as68 .s file with the packed
bytes. This is the steel "quarter tile": every steel cell is composed
from 1, 2, or 4 copies of this one tile (full cell = 2x2, top/bottom
border row = 1x2, left/right border column = 2x1, corner = 1x1) so the
texture always tiles seamlessly at every border seam -- see
asm/display.s's blit_steel_full/blit_steel_half/blit_steel_vert/
blit_steel_corner.

Same mode 8 word layout/palette order as tools/png2sprites.py (kept in
sync manually since this is a single fixed tile, not a sprite sheet)."""
import sys
from pathlib import Path
from PIL import Image

PALETTE = [
    (0x00, 0x00, 0x00),  # 0 black
    (0x00, 0x00, 0xFF),  # 1 blue
    (0xFF, 0x00, 0x00),  # 2 red
    (0xFF, 0x00, 0xFF),  # 3 magenta
    (0x00, 0xFF, 0x00),  # 4 green
    (0x00, 0xFF, 0xFF),  # 5 cyan
    (0xFF, 0xFF, 0x00),  # 6 yellow
    (0xFF, 0xFF, 0xFF),  # 7 white
]
TILE_W = 12
TILE_H = 16


def colour_index(rgb):
    return PALETTE.index(rgb)


def encode_tile(img):
    out = []
    for y in range(TILE_H):
        for g in range(TILE_W // 4):
            even = 0
            odd = 0
            for px in range(4):
                x = g * 4 + px
                idx = colour_index(img.getpixel((x, y)))
                gbit = (idx >> 2) & 1
                rbit = (idx >> 1) & 1
                bbit = idx & 1
                shift = (3 - px) * 2
                even |= (gbit << 1 | 0) << shift
                odd |= (rbit << 1 | bbit) << shift
            out.append(even & 0xFF)
            out.append(odd & 0xFF)
    return out


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("assets/steel_sub.png")
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("asm/steel_sub_data.s")

    img = Image.open(src).convert("RGB")
    assert img.size == (TILE_W, TILE_H), f"expected {TILE_W}x{TILE_H}, got {img.size}"

    tile_bytes = encode_tile(img)
    lines = []
    lines.append("; steel_sub_data.s -- auto-generated by tools/png2steel_sub.py")
    lines.append(f"; from {src.name}. Do not edit by hand -- regenerate instead.")
    lines.append(f"; 1 tile, {TILE_W}x{TILE_H} mode 8 pixels, {len(tile_bytes)} bytes.")
    lines.append("")
    lines.append("\t.sect\t.data")
    lines.append("\t.extern\t_steel_sub_data")
    lines.append("\t.even")
    lines.append("_steel_sub_data:")

    for row in range(0, len(tile_bytes), 16):
        chunk = tile_bytes[row:row + 16]
        hex_list = ",".join(f"${b:02x}" for b in chunk)
        lines.append(f"\t.data1\t{hex_list}")

    lines.append("")
    dst.write_text("\n".join(lines) + "\n")
    print(f"Wrote {dst} ({len(tile_bytes)} bytes)")


if __name__ == "__main__":
    main()
