#!/usr/bin/env python3
"""Convert blocks.png (10 tiles, 24x32, pure QL mode-8 palette) into raw
mode 8 pixel data and emit an as68 .s file with the packed bytes.

Tiles are 24x32 (not square) so they render as visual squares on real
QL hardware: mode 8 pixels are physically wider than tall by the same
4:3 ratio as the screen (a square 256x256 pixel grid stretched to fill
a physical 4:3 frame), so a tile needs the inverse 3:4 ratio to cancel
that out. 24 is the smallest multiple of 3 close to the original 16px
width, giving a clean 24x32 with no rounding.

Mode 8 word layout (docs/takeover.md in tomconte/ql, verified against
game8.asm's spr_addr bit math): each 4-pixel group is 2 bytes --
  even byte (G/F plane): px0.G px0.F px1.G px1.F px2.G px2.F px3.G px3.F
  odd  byte (R/B plane): px0.R px0.B px1.R px1.B px2.R px2.B px3.R px3.B
bit7 is the leftmost pixel of the group (px0), bit0 the rightmost (px3).
F (hardware flash) is always 0 here. Colour index -> G,R,B bits: matches
the QL's fixed palette order (black,blue,red,magenta,green,cyan,yellow,
white), i.e. index = G*4 + R*2 + B, which is exactly game.js's PALETTE
array order -- so this script's PALETTE below must stay in that order.
"""
import sys
from pathlib import Path
from PIL import Image

PALETTE = [
    (0x00, 0x00, 0x00),  # 0 black
    (0x00, 0x00, 0xFF),  # 1 blue
    (0xFF, 0x00, 0x00),  # 2 red
    (0xFF, 0x00, 0xFF),  # 3 magenta
    (0x00, 0xFF, 0x00),  # 4 green
    (0x00, 0xFF, 0xFF),  # 5 cyan
    (0xFF, 0xFF, 0x00),  # 6 yellow
    (0xFF, 0xFF, 0xFF),  # 7 white
]
TILE_W = 24
TILE_H = 32


def colour_index(rgb):
    return PALETTE.index(rgb)


def encode_tile(img, tile_x0):
    """Returns a flat list of bytes: TILE_H rows * (TILE_W/4*2) bytes."""
    out = []
    for y in range(TILE_H):
        for g in range(TILE_W // 4):
            even = 0
            odd = 0
            for px in range(4):
                x = tile_x0 + g * 4 + px
                idx = colour_index(img.getpixel((x, y)))
                gbit = (idx >> 2) & 1
                rbit = (idx >> 1) & 1
                bbit = idx & 1
                shift = (3 - px) * 2
                even |= (gbit << 1 | 0) << shift  # F bit stays 0
                odd |= (rbit << 1 | bbit) << shift
            out.append(even & 0xFF)
            out.append(odd & 0xFF)
    return out


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("blocks.png")
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("asm/sprites_data.s")

    img = Image.open(src).convert("RGB")
    n_tiles = img.width // TILE_W
    assert img.height == TILE_H, f"expected height {TILE_H}, got {img.height}"

    bytes_per_tile = TILE_H * (TILE_W // 4 * 2)
    lines = []
    lines.append("; sprites_data.s -- auto-generated by tools/png2sprites.py from")
    lines.append(f"; {src.name}. Do not edit by hand -- regenerate instead.")
    lines.append(f"; {n_tiles} tiles, {TILE_W}x{TILE_H} mode 8 pixels, {bytes_per_tile} bytes each.")
    lines.append("")
    lines.append("\t.sect\t.data")
    lines.append("\t.extern\t_sprite_data")
    lines.append("\t.even")
    lines.append("_sprite_data:")

    for t in range(n_tiles):
        tile_bytes = encode_tile(img, t * TILE_W)
        lines.append(f"; tile {t}")
        for row in range(0, len(tile_bytes), 16):
            chunk = tile_bytes[row:row + 16]
            hex_list = ",".join(f"${b:02x}" for b in chunk)
            lines.append(f"\t.data1\t{hex_list}")

    lines.append("")
    dst.write_text("\n".join(lines) + "\n")
    print(f"Wrote {dst} ({n_tiles} tiles)")


if __name__ == "__main__":
    main()
